name: Develop
on:
  pull_request:
    branches: [ dev ]
jobs:
  detect:
    steps:
      - uses: actions/checkout@v5
        with:
          ref: dev
          fetch-depth: 2
      - uses: tj-actions/changed-files@v47
        with:
          base_branch: dev
        id: changed
      - uses: ${{ vars.SCRIPT_REPO }}/.github/actions/${{ vars.DETECT_SCRIPT }}@main
        with:
          changed_files: ${{ toJSON(steps.changed.outputs.all_changed_files) }}
        id: matrix
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    if: startsWith(github.ref_name, 'feature/') ||
        startsWith(github.ref_name, 'bugfix/') ||
        startsWith(github.ref_name, 'hotfix/')
    runs-on: ubuntu-latest
  develop:
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            ${{ matrix.scope }}/${{ matrix.service }}
            **/*.gradle.kts
            gradle/
            gradlew
            Dockerfile
      - uses: ${{ vars.ACTION_REPO }}/.github/actions/${{ vars.DEV_ACTION }}@main
        with:
          scope: ${{ matrix.scope }}
          service: ${{ matrix.service }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.STARTER_PAT }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.matrix) }}
    needs: detect
    runs-on: ubuntu-latest
