name: Ensure Publish
on:
  pull_request:
    branches: [ main ]
jobs:
  detect:
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - uses: tj-actions/changed-files@v47
        id: changed
      - uses: ${{ vars.REPO_SCRIPT }}/.github/actions/${{ vars.SCRIPT_DETECT }}@main
        with:
          changed: ${{ toJSON(steps.changed.outputs.all_changed_files) }}
        id: matrix
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    if: startsWith(github.ref_name, 'dev') ||
      startsWith(github.ref_name, 'hotfix/')
    runs-on: ubuntu-latest
  ensure-publish:
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            ${{ matrix.name }}
            gradle/
            gradlew
            build.gradle.kts
            settings.gradle.kts
      - uses: ${{ vars.REPO_ACTION }}/.github/actions/${{ vars.ACTION_ENSURE_PUBLISH }}@main
        with:
          service: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.matrix) }}
    needs: detect
    runs-on: ubuntu-latest
