name: Prepare Release
on:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  resolve-image:
    steps:
      - uses: actions/checkout@v4
        with:
          repository: hamsaqua/script
          fetch-depth: 1
          path: ${{ runner.temp }}/script
      - uses: actions/checkout@v4
        with:
          ref: dev
          sparse-checkout: settings.gradle.kts
      - run: bash ${{ runner.temp }}/script/app/pre-release
        id: name
      - run: echo "version=$(date -u +'%Y%m%d')" >> "$GITHUB_OUTPUT"
        id: version
    outputs:
      matrix: ${{ steps.name.outputs.matrix }}
      version: ${{ steps.version.outputs.version }}
    runs-on: ubuntu-latest
  pre-release:
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - uses: hamsaqua/action/.github/actions/pre-release-app@main
        with:
          scope: ${{ matrix.scope }}
          service: ${{ matrix.service }}
          version: ${{ needs.resolve-image.outputs.version }}
          key: ${{ secrets.APP_DK }}
          pat: ${{ secrets.APP_PAT }}
    needs: resolve-image
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.resolve-image.outputs.matrix) }}
    runs-on: ubuntu-latest
