name: Prepare Release
on:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  resolve-version:
    steps:
      - uses: actions/checkout@v4
        with:
          repository: hamsaqua/script
          fetch-depth: 1
          path: ${{ runner.temp }}/script
      - uses: actions/checkout@v4
        with:
          ref: dev
          sparse-checkout: settings.gradle.kts
      - run: bash ${{ runner.temp }}/script/app/pre-release
        env:
          DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPO }}
          DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        id: resolve
    outputs:
      matrix: ${{ steps.resolve.outputs.matrix }}
    runs-on: ubuntu-latest
  pre-release:
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - uses: hamsaqua/action/.github/actions/pre-release-app@main
        with:
          scope: ${{ matrix.scope }}
          service: ${{ matrix.service }}
          version: ${{ matrix.version }}
          key: ${{ secrets.APP_DK }}
          pat: ${ secrets.APP_PAT }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.resolve-version.outputs.matrix) }}
    needs: resolve-version
    runs-on: ubuntu-latest
