name: Publish
on:
  pull_request:
    branches: [ main ]
jobs:
  detect:
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: tj-actions/changed-files@v47
        id: changed
      - uses: $OWNER/$REPO/.github/actions/$SCRIPT@main
        with:
          changed: ${{ toJSON(steps.changed.outputs.all_changed_files) }}
        id: matrix
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    env:
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ vars.REPO_SCRIPT }}
      SCRIPT: ${{ vars.SCRIPT_DETECT }}
    if: github.head_ref == 'dev' ||
      startsWith(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest
  publish:
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: |
            ${{ matrix.name }}
            gradle/
            gradlew
            build.gradle.kts
            settings.gradle.kts
      - uses: $OWNER/$REPO/.github/actions/$ACTION@main
        with:
          module: ${{ matrix.name }}
          tld: ${{ vars.TLD }}
          event: ${{ vars.EVENT }}
          core_pat: ${{ secrets.PAT_CORE }}
          adapters_pat: ${{ secrets.PAT_ADAPTERS }}
    env:
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ vars.REPO_SCRIPT }}
      ACTION: ${{ vars.ACTION_PUBLISH }}
      MODULE: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.matrix) }}
    needs: detect
    runs-on: ubuntu-latest
