name: Release
on:
  push:
    branches: [ main ]
jobs:
  release:
    steps:
      - uses: actions/checkout@v4
        with:
          repository: hamsaqua/script
          fetch-depth: 1
          path: ${{ runner.temp }}/script
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - run: bash ${{ runner.temp }}/script/app/release
        id: parse
      - uses: hamsaqua/action/.github/actions/release@main
        with:
          scope: ${{ steps.parse.outputs.scope }}
          service: ${{ steps.parse.outputs.service }}
          version: ${{ github.sha }}
          docker_user: ${{ vars.DOCKERHUB_USER }}
          docker_repo: ${{ vars.DOCKERHUB_REPO }}
          docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
          slack: ${{ secrets.SLACK_WEBHOOK_URL }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram: ${{ secrets.TELEGRAM_CHAT_ID }}
          discord: ${{ secrets.DISCORD_WEBHOOK_URL }}
          pat: ${{ secrets.APP_DEPLOY_PAT }}
    runs-on: ubuntu-latest
