name: Release
on:
  push:
    branches: [ main ]
jobs:
  detect:
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - uses: tj-actions/changed-files@v47
        with:
          base_branch: main
        id: changed
      - uses: ${{ vars.REPO_SCRIPT }}/.github/actions/${{ vars.SCRIPT_DETECT }}@main
        with:
          changed: ${{ toJSON(steps.changed.outputs.all_changed_files) }}
        id: matrix
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    runs-on: ubuntu-latest
  release:
    steps:
      - uses: actions/checkout@v5
      - uses: ${{ vars.REPO_ACTION }}/.github/actions/${{ vars.ACTION_RELEASE }}@main
        with:
          scope: ${{ matrix.scope }}
          service: ${{ matrix.service }}
          repo: ${{ vars.REPO_DEPLOY }}
          event: ${{ vars.EVENT_RELEASE }}
          docker_user: ${{ vars.DOCKERHUB_USER }}
          docker_repo: ${{ vars.DOCKERHUB_REPO }}
          pat: ${{ secrets.PAT_DEPLOY }}
          docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
          slack: ${{ secrets.SLACK_WEBHOOK }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram: ${{ secrets.TELEGRAM_CHAT }}
          discord: ${{ secrets.DISCORD_WEBHOOK }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.matrix) }}
    needs: detect
    runs-on: ubuntu-latest
