name: Settings
on:
  push:
    branches: [ main ]
    paths: [ settings.gradle ]
jobs:
  settings:
    steps:
      - uses: actions/checkout@v4
        with:
          repository: hamsaqua/script
          fetch-depth: 1
          path: ${{ runner.temp }}/script
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          sparse-checkout: settings.gradle
      - run: bash ${{ runner.temp }}/script/app/settings
        env:
          DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPO }}
      - uses: wliamp/action/.github/actions/settings@main
        with:
          in_key: ${{ secrets.JAVA_DK }}
          ex_key: ${{ secrets.JAVA_DEPLOYMENT_DK }}
    runs-on: ubuntu-latest
