name: Settings
on:
  push:
    branches: [ main ]
    paths: [ settings.gradle.kts ]
jobs:
  settings:
    steps:
      - uses: actions/checkout@v4
        with:
          repository: hamsaqua/script
          fetch-depth: 1
          path: ${{ runner.temp }}/script
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          sparse-checkout: settings.gradle.kts
      - run: bash ${{ runner.temp }}/script/app/settings
        env:
          DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPO }}
      - uses: hamsaqua/action/.github/actions/settings-app@main
        with:
          in_key: ${{ secrets.APP_DK }}
          ex_key: ${{ secrets.APP_DEPLOY_DK }}
    runs-on: ubuntu-latest
