name: Settings
on:
  repository_dispatch:
    types: service_initialed
jobs:
  settings:
    steps:
      - uses: actions/checkout@v4
        with:
          repository: hamsaqua/script
          fetch-depth: 1
          path: ${{ runner.temp }}/script
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: bash ${{ runner.temp }}/script/app/settings
      - uses: hamsaqua/action/.github/actions/settings@main
        with:
          ssh: ${{ secrets.SSH }}
    runs-on: ubuntu-latest
