name: Settings
on:
  workflow_run:
    workflows: [ Initial Service ]
    types: [ completed ]
jobs:
  settings:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: dev
      - uses: actions/checkout@v5
        with:
          repository: ${{ vars.REPO_SUPPORT }}
          path: ${{ runner.temp }}
      - uses: ${{ vars.REPO_SCRIPT }}/.github/actions/${{ vars.SCRIPT_SETTINGS }}@main
      - uses: ${{ vars.REPO_ACTION }}/.github/actions/${{ vars.ACTION_SETTINGS }}@main
        with:
          release_ssh: ${{ secrets.SSH_RELEASE }}
          support_ssh: ${{ secrets.SSH_SUPPORT }}
    runs-on: ubuntu-latest
