name: Settings
on:
  workflow_run:
    workflows: [ Initial Service ]
    types: [ completed ]
jobs:
  settings:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: ${{ vars.SUPPORT_REPO }}
          path: ${{ runner.temp }}
      - uses: ${{ vars.SCRIPT_REPO }}/.github/actions/${{ vars.SETTINGS_SCRIPT }}@main
      - uses: ${{ vars.ACTION_REPO }}/.github/actions/${{ vars.SETTINGS_ACTION }}@main
        with:
          release_ssh: ${{ secrets.RELEASE_SSH }}
          support_ssh: ${{ secrets.SUPPORT_SSH }}
    runs-on: ubuntu-latest
